# Generated by Django 4.0.2 on 2022-02-07 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_alter_myuser_last_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_action',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 8, 0, 3, 16, 887200)),
        ),
    ]
